### PR TITLE
Add `count` command

### PR DESCRIPTION
**Pull request by pborzenkov**
`count` counts the number of songs and their total playtime matching the given `filter`.

### CODE REVIEW

**Comment by elomatreb** [comment]
Thanks for the PR. I think it would be best if you created a dedicated response type to expose the fields properly. `count` and `playtime` aren't tags, but using the `List` response type represents them as such. The grouping feature makes this pretty complicated, I still haven't figured out a nice way to represent the response of the `list` command in general :/

**Comment by pborzenkov** [comment]
> I think it would be best if you created a dedicated response type to expose the fields properly.

That was my initial idea, by the ability to group results by some tag makes the response a bit too flexible. It basically suffers from the same complexity as `List`. One of the ideas that I had is to make `Count` command generic and allow a user to pass response type. Let me know what do you think.

**Comment by elomatreb** [comment]
I've implemented a version of the command in a920839276241b76468090c309d1e2ab3f326c1f, does this fit your needs?

I solved the grouping problem by splitting the command into two, one for grouped and one for ungrouped responses.

**Comment by pborzenkov** [comment]
> does this fit your needs?

@elomatreb It does!

Very nice implementation! Thank you.

**Comment by pborzenkov** [comment]
I will close this PR in favor of your implementation.

**Comment by elomatreb** [comment]
I've just published crate version 1.0 that includes this implementation.

**Pull request closed without merging**
